frr defaults traditional
hostname ce2
log stdout informational
service integrated-vtysh-config
no ipv6 forwarding
interface lo
 ip address 10.254.0.6/32
interface to-pe2
interface to-host2
ip prefix-list CUSTOMER seq 10 permit 10.200.8.0/29
ip prefix-list CUSTOMER seq 20 permit 10.200.9.0/29
router bgp 65002
 bgp router-id 10.254.0.6
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.200.7.3 remote-as 65000
 address-family ipv4 unicast
  neighbor 10.200.7.3 activate
  neighbor 10.200.7.3 prefix-list CUSTOMER in
  neighbor 10.200.7.3 prefix-list CUSTOMER out
  network 10.200.9.0/29
 exit-address-family
!
