frr defaults traditional
hostname p2
log stdout informational
service integrated-vtysh-config
no ipv6 forwarding
interface lo
 ip address 10.254.0.2/32
interface to-p1
 ip ospf area 0
 ip ospf network point-to-point
interface to-pe1
 ip ospf area 0
 ip ospf network point-to-point
interface to-pe2
 ip ospf area 0
 ip ospf network point-to-point
interface lo
 ip ospf area 0
router ospf
 ospf router-id 10.254.0.2
 passive-interface lo
ip prefix-list CUSTOMER seq 10 permit 10.200.8.0/29
ip prefix-list CUSTOMER seq 20 permit 10.200.9.0/29
router bgp 65000
 bgp router-id 10.254.0.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.254.0.1 remote-as 65000
 neighbor 10.254.0.1 update-source lo
 neighbor 10.254.0.3 remote-as 65000
 neighbor 10.254.0.3 update-source lo
 neighbor 10.254.0.4 remote-as 65000
 neighbor 10.254.0.4 update-source lo
 address-family ipv4 unicast
  neighbor 10.254.0.1 activate
  neighbor 10.254.0.1 prefix-list CUSTOMER in
  neighbor 10.254.0.1 prefix-list CUSTOMER out
  neighbor 10.254.0.3 activate
  neighbor 10.254.0.3 prefix-list CUSTOMER in
  neighbor 10.254.0.3 prefix-list CUSTOMER out
  neighbor 10.254.0.4 activate
  neighbor 10.254.0.4 prefix-list CUSTOMER in
  neighbor 10.254.0.4 prefix-list CUSTOMER out
 exit-address-family
!
